#!/bin/sh

case "$1" in
  start)
        if [ -f /proc/sys/net/netfilter/nf_conntrack_helper ]
        then
            echo 0 > /proc/sys/net/netfilter/nf_conntrack_helper
        fi
        echo "Trying to mount custfs on NAND..."
        mkdir -p /mnt/custfs
        if cat /proc/mtd | grep -q '^mtd8: .*\"ncustfs\"$'; then
            /usr/sbin/ubiattach -m 8 -d 1
            /bin/mount -t ubifs /dev/ubi1_0 /mnt/custfs/
        else
        if cat /proc/mtd | grep -q '^mtd4: .*\"ncustfs\"$'; then
            /usr/sbin/ubiattach -m 4 -d 1
            /bin/mount -t ubifs /dev/ubi1_0 /mnt/custfs/
#        else
#        if cat /proc/mtd | grep -q '^mtd4: .*\"custfs\"$'; then
#            /bin/mount -t jffs2 /dev/mtdblock4 /mnt/custfs/      
#        fi
        fi
        fi
         ;;
  stop)
         ;;
  restart|reload)
         ;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
